config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  resources :homepage, only: [:index] do
  end
  resources :hair, only: [:index] do
  end
  resources :modern, only: [:index] do
  end
  resources :notes, only: [:index, :new] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hair_controller.rb
class HairController < ApplicationController
  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index 
  end
end

app/controllers/modern_controller.rb
class ModernController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index 
  end

  def new 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hair_helper.rb
module HairHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/modern_helper.rb
module ModernHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/hair/index.html.erb
<div class="hair">
  <header>
    <div class="heading">
      <h1 class="title">Hair OLIVE</h1>
      <p class="heading-sentence">美しさを引き出すヘアスタイルのご提案。</p>
    </div>

    <div class="navbar">
      <ul>
        <li>サロンガイド</li>
        <li>メニュー</li>
        <li>スタッフ一覧</li>
        <li>ギャラリー</li>
        <li>アクセス</li>
        <li>ブログ</li>
      </ul>
    </div>
  </header>

  <div class="contents clearfix">
    <div class="left-content">
      <h2>新着情報</h2>
      <table>
        <tr>
          <th>日にち</th>
          <th>ニュース</th>
        </tr>
        <tr>
          <td>2014/10/06</td>
          <td>【新規のお客さま限定】<strong>10％OFF</strong>キャンペーン</td>
        </tr>
        <tr>
          <td>2014/10/03</td>
          <td>うれしい<em>ポイントアップキャンペーン</em></td>
        </tr>
        <tr>
          <td>2014/09/27</td>
          <td>2015年成人式 ご予約承ります</td>
        </tr>
      </table>
      <h2>スタイリスト紹介</h2>
      <ul>
        <li>
          <img src="images/sample.1.jpeg" alt="staff1" class="stylist-image">
          <h4 class="stylist-name">鈴木</h4>
        </li>
        <li>
          <img src="images/sample.jpeg" alt="staff2" class="stylist-image">
          <h4 class="stylist-name">佐藤</h4>
        </li>
      </ul>
    </div>

    <div class="right-content">
      <h3>15th Anniversary</h3>
      <p>
        15周年記念キャンペーン
        <a href="https://tech-camp.in/expert">⇒詳しくはこちら</a>
      </p>
        <h3>アプリで簡単予約</h3>
      <p>
        <a href="https://itunes.apple.com">App Store</a>
        <a href="https://store.google.com">Google Play</a>
      </p>
      <h3>メールで予約</h3>
        <form>
          <input type="text" placeholder="名前を入力してください"><br>
          <textarea placeholder="予約日時やご要望をお書きください"></textarea><br>
          <label>
            <input type="radio" name="RadioGroup1" value="0">男性
          </label><br>
          <label>
            <input type="radio" name="RadioGroup1" value="1">女性
          </label><br>
          <select>
            <option value="0">学生</option>
            <option value="1">社会人</option>
          </select>
          <div class="questionaire">
            Hair OLIVEの利用は初めてですか？<br>
            <label>
              <input type="checkbox" name="Checkbox" value="0">
                初めて
            </label>
            <label>
              <input type="checkbox" name="Checkbox" value="1">
                2回目以降
            </label><br>
          </div>
          <input type="submit" value="予約メールを送る">
        </form>
    </div>
  </div>
  <footer>
    <small>Copyright(C) Hair OLIVE ALL RIGHTS RESERVED.</small>
  </footer>
</div>

app/views/homepage/index.html.erb
<header>
  <h1>TECH CAMP 復習</h1>
</header>
<div class="menu">
  <%= link_to "Hair OLIVE", hair_index_path , class: "hair" %>
  <%= link_to "Modern view", modern_index_path , class: "hair" %>
  <%= link_to "Note",  notes_path , class: "hair" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomepageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modern/index.html.erb
<div class="modern">
  <header>
    <h1><a href="#">Prot-type</a></h1>
    <nav>
      <ul class="header-links">
        <li class="header-link"><a href="#">About</a></li>
        <li class="header-link"><a href="#">Service</a></li>
        <li class="header-link"><a href="#">Contents</a></li>
      </ul>
    </nav>
  </header>
   <main>
    <section class="fv-section">
      <p class="main-copy">プロトタイピングをサービス改善のエンジンに</p>
      <p class="fv-text">ユーザーを「ファン」に変えるプロトタイピング推進ツール</p>
      <a href="#" class="cta-btn">使ってみる</a>
    </section>
     <section class="card-section">
      <h2 class="card-section-title">サービスの成功にコミットする企業に選ばれました</h2>
      <ul class="card-list">
        <li class="card-item">
          <div class="card-img">
            <img src="/images/img_cliants01.png" alt="クライアントの画像1">
            <h3>株式会社 gaga</h3>
          </div>
          <p class="card-text">プロトタイピングを推進する強力なツール。チーム内での認識共有のレベルが上がった。</p>
        </li>
        <li class="card-item">
          <div class="card-img">
            <img src="/images/img_cliants02.png" alt="クライアントの画像2">
            <h3>株式会社 Beatles</h3>
          </div>
          <p class="card-text">事前にユーザーの反応が知ることができるため、サービス完成後の手戻りがなくなった。</p>
        </li>
        <li class="card-item">
          <div class="card-img">
            <img src="/images/img_cliants03.png" alt="クライアントの画像3">
            <h3>株式会社 LEMON</h3>
          </div>
          <p class="card-text">プロトタイプを作成することによって、クライアントへのプレゼンに説得力が増した。</p>
        </li>
      </ul>
    </section>
  </main>
  <footer>
    <small>Prot-type all rights reserved</small>
  </footer>
</div>

app/views/notes/index.html.erb
<%= link_to "新規メモ", new_note_path , class: "hair" %>
<%= form_tag('/posts', method: :post) do %> 
  <input type="text" name="content"> 
  <input type="submit" value="投稿する">
<% end %>

app/views/notes/new.html.erb
<h1>新規投稿ページ</h1>